app:
  name: "topgun-services"
  env: "production"
  port:
    http: 8080
    https: 8443
  path:
    cert: "./internal/assets/uat/tls/uat.crt"
    priv: "./internal/assets/uat/tls/uat.key"
    ca: "./internal/assets/uat/tls/rootCA.crt"
    log: "./log"
    image: "./uploads/images"
    file: "./uploads/files"
  frontend:
    base_url: "localhost:4200"

db:
  mariadb:
    sock: "/var/run/mysqld/mysqld.sock"
    host: "localhost"
    port: 3306
    username: ""
    password: ""
    db_name: ""
    conn:
      min: 1
      max: 2
  postgres:
    sock: "/var/run/postgresql"
    host: "localhost"
    # host: "localhost"
    port: 5432
    username: "topgun"
    password: "vWF45jd7NQndasdczxSAwr8674y451GJP1IVAc2rx"
    db_name: "topgun"
    conn:
      min: 1
      max: 2
  sqlite:
    db_name: "internal/assets/uat/log.sqlite"
  redis:
    host: ""
    # host: "localhost"
    port: 12006
    username: ""
    password: ""
    db_name: 0
    minute: 5
jwt:
  # openssl ecparam -name prime256v1 -genkey -noout -out privkey.pem
  private: "./internal/assets/uat/jwt/privkey.pem"
  # openssl ec -in privkey.pem -pubout -out pubkey.pem
  public: "./internal/assets/uat/jwt/pubkey.pem"

mqtt:
  broker: "tcp://mosquitto:1883"
  client_id: "topgun-services"
  topic: "topgun/ai"
